services:
  celery:
    image: booking-api-image:latest
    container_name: hotels_celery
    env_file:
      - ${APP_ENV_FILE:-.env}
    command:  ["poetry", "run", "celery", "-A", "tasks.celery_app:celery_app", "worker", "-l", "info"]
    networks:
      - hotels_network
    volumes:
      # Слева путь на ПК, справа — путь внутри контейнера
      - ./src/static/images:/app/src/static/images

  celery_beat:
    image: booking-api-image:latest
    container_name: hotels_celery_beat
    env_file:
      - ${APP_ENV_FILE:-.env}
    command: [ "poetry", "run", "celery", "-A", "tasks.celery_app:celery_app", "beat", "-l", "info" ]
    networks:
      - hotels_network

  backend:
    image: booking-api-image:latest
    container_name: hotels_backend
    env_file:
      - ${APP_ENV_FILE:-.env}
    networks:
      - hotels_network
    volumes:
      # Слева путь на ПК, справа — путь внутри контейнера
      - ./src/static/images:/app/src/static/images
networks:
  hotels_network:
    external: true
