services:
  postgres:
    image: postgres:16-alpine
    container_name: hotels_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hotels_network
  redis:
    image: redis:7-alpine
    container_name: hotels_redis
    restart: unless-stopped
    env_file:
      - .env
    command:
      - sh
      - -c
      - exec redis-server --requirepass "$$REDIS_PASSWORD"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - hotels_network

  celery:
    build: .
    container_name: hotels_celery
    restart: unless-stopped
    command:  ["poetry", "run", "celery", "-A", "tasks.celery_app:celery_app", "worker", "-l", "info"]
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - hotels_network
    volumes:
      # Слева путь на ПК, справа — путь внутри контейнера
      - ./src/static/images:/app/src/static/images

  celery_beat:
    build: .
    container_name: hotels_celery_beat
    restart: unless-stopped
    command: [ "poetry", "run", "celery", "-A", "tasks.celery_app:celery_app", "beat", "-l", "info" ]
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - hotels_network

  backend:
    build: .
    container_name: hotels_backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - hotels_network
    volumes:
      # Слева путь на ПК, справа — путь внутри контейнера
      - ./src/static/images:/app/src/static/images

  nginx_service:
    image: nginx
    container_name: hotels_nginx
    depends_on:
      - backend
    volumes:
      # Слева путь на ПК, справа — путь внутри контейнера
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "443:443"
    networks:
      - hotels_network

volumes:
  postgres_data:
networks:
  hotels_network:
    driver: bridge