events {
}

http {
    server {
        listen 443 ssl;
        location / {
            proxy_pass http://backend:8000/;
        }
    }
;     ssl_certificate /etc/letsencrypt/live/nina-nikitenko.ru/fullchain.pem;
;     ssl_certificate_key /etc/letsencrypt/live/nina-nikitenko.ru/privkey.pem;
;     include /etc/letsencrypt/options-ssl-nginx.conf;
;     ssl_dhparam /etc/letsencrypt/ssl_dhparams.pem;
}