"""hotels_without_stars

Revision ID: e18ff2f3f1fd
Revises: 23a08fd14361
Create Date: 2026-05-07 07:33:48.319605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e18ff2f3f1fd"
down_revision: Union[str, Sequence[str], None] = "23a08fd14361"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("hotels", "stars", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("hotels", "stars", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
