"""add_facilities_uniq_constraint

Revision ID: 23a08fd14361
Revises: 3ca2aa984cdd
Create Date: 2026-03-02 11:43:54.431525

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "23a08fd14361"
down_revision: Union[str, Sequence[str], None] = "3ca2aa984cdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_room_facility", "rooms_facilities", ["room_id", "facility_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_room_facility", "rooms_facilities", type_="unique")
    # ### end Alembic commands ###
