"""add_facilities

Revision ID: 3ca2aa984cdd
Revises: dcb43a10a45b
Create Date: 2026-03-01 09:30:09.416414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ca2aa984cdd"
down_revision: Union[str, Sequence[str], None] = "dcb43a10a45b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facilities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms_facilities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("room_id", sa.BigInteger(), nullable=False),
        sa.Column("facility_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rooms_facilities_facility_id"),
        "rooms_facilities",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rooms_facilities_room_id"),
        "rooms_facilities",
        ["room_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rooms_facilities_room_id"), table_name="rooms_facilities"
    )
    op.drop_index(
        op.f("ix_rooms_facilities_facility_id"), table_name="rooms_facilities"
    )
    op.drop_table("rooms_facilities")
    op.drop_table("facilities")
    # ### end Alembic commands ###
